apiVersion: apps/v1
kind: Deployment
metadata:
  name: maaspal
  namespace: maaspal
  labels:
    app: maaspal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maaspal
  template:
    metadata:
      labels:
        app: maaspal
    spec:
      serviceAccountName: maaspal
      containers:
        - name: api
          image: quay.io/rh-aiservices-bu/maaspal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: maaspal-global-config
          volumeMounts:
            - name: data
              mountPath: /data
            - name: scenarios
              mountPath: /app/scenarios
          readinessProbe:
            httpGet:
              path: /api/scenarios
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: maaspal-data
        - name: scenarios
          configMap:
            name: maaspal-scenarios
