apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kratos

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - configmap-global.yaml
  - configmap-scenarios.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
