apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maaspal
  namespace: maaspal
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maaspal
  namespace: maaspal
subjects:
  - kind: ServiceAccount
    name: maaspal
    namespace: maaspal
roleRef:
  kind: Role
  name: maaspal
  apiGroup: rbac.authorization.k8s.io
