apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kratos
  namespace: kratos
spec:
  to:
    kind: Service
    name: kratos
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
