apiVersion: v1
kind: ServiceAccount
metadata:
  name: maaspal
  namespace: maaspal
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"maaspal"}}'
